-- Table structure for `batch_step_records`
SET NAMES utf8mb4;
USE `company_test`;

DROP TABLE IF EXISTS `batch_step_records`;
CREATE TABLE `batch_step_records` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT COMMENT '主键',
  `batch_id` bigint unsigned NOT NULL COMMENT '生产批次ID',
  `process_route_steps_id` bigint unsigned NOT NULL COMMENT '工艺路线工序ID',
  `responsible_user_id` bigint unsigned DEFAULT NULL COMMENT '负责人ID',
  `sop_file_id` bigint unsigned DEFAULT NULL COMMENT '当前批次工序实际使用的参考文件ID',
  `output_quantity` decimal(12,4) DEFAULT NULL COMMENT '完成数量',
  `abnormal_quantity` decimal(12,4) DEFAULT NULL COMMENT '异常数量',
  `return_quantity` decimal(12,4) DEFAULT NULL COMMENT '返工数量',
  `parameter_definitions` json DEFAULT NULL COMMENT '生成批次工序时固化的重要参数定义快照',
  `parameter_values` json DEFAULT NULL COMMENT '本次报工填写的工序重要参数值',
  `status` varchar(50) NOT NULL DEFAULT 'pending' COMMENT 'pending/doing/completed/abnormal/skipped',
  `started_at` datetime DEFAULT NULL COMMENT '开始时间',
  `completed_at` datetime DEFAULT NULL COMMENT '完成时间',
  `remark` text COMMENT '备注',
  `created_by` bigint unsigned DEFAULT NULL COMMENT '创建人',
  `created_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `updated_by` bigint unsigned DEFAULT NULL COMMENT '更新人',
  `updated_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  `is_deleted` tinyint NOT NULL DEFAULT '0' COMMENT '软删除标记',
  `deleted_by` bigint unsigned DEFAULT NULL COMMENT '删除人',
  `deleted_at` datetime DEFAULT NULL COMMENT '删除时间',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_batch_step_records_batch_step_deleted` (`batch_id`,`process_route_steps_id`,`is_deleted`),
  KEY `idx_batch_step_records_batch_id` (`batch_id`),
  KEY `idx_batch_step_records_process_route_steps_id` (`process_route_steps_id`),
  KEY `idx_batch_step_records_responsible_user_id` (`responsible_user_id`),
  KEY `idx_batch_step_records_sop_file_id` (`sop_file_id`),
  KEY `idx_batch_step_records_status` (`status`),
  KEY `idx_batch_step_records_is_deleted` (`is_deleted`),
  KEY `idx_batch_step_records_created_by` (`created_by`),
  KEY `idx_batch_step_records_updated_by` (`updated_by`),
  KEY `idx_batch_step_records_deleted_by` (`deleted_by`),
  CONSTRAINT `fk_batch_step_records_batch_id` FOREIGN KEY (`batch_id`) REFERENCES `production_batches` (`id`) ON DELETE CASCADE,
  CONSTRAINT `fk_batch_step_records_created_by` FOREIGN KEY (`created_by`) REFERENCES `users` (`id`) ON DELETE SET NULL,
  CONSTRAINT `fk_batch_step_records_deleted_by` FOREIGN KEY (`deleted_by`) REFERENCES `users` (`id`) ON DELETE SET NULL,
  CONSTRAINT `fk_batch_step_records_process_route_steps_id` FOREIGN KEY (`process_route_steps_id`) REFERENCES `process_route_steps` (`id`) ON DELETE RESTRICT,
  CONSTRAINT `fk_batch_step_records_responsible_user_id` FOREIGN KEY (`responsible_user_id`) REFERENCES `users` (`id`) ON DELETE SET NULL,
  CONSTRAINT `fk_batch_step_records_sop_file_id` FOREIGN KEY (`sop_file_id`) REFERENCES `technical_files` (`id`) ON DELETE SET NULL,
  CONSTRAINT `fk_batch_step_records_updated_by` FOREIGN KEY (`updated_by`) REFERENCES `users` (`id`) ON DELETE SET NULL,
  CONSTRAINT `chk_batch_step_records_abnormal_quantity` CHECK ((`abnormal_quantity` IS NULL) OR (`abnormal_quantity` >= 0)),
  CONSTRAINT `chk_batch_step_records_output_quantity` CHECK ((`output_quantity` IS NULL) OR (`output_quantity` >= 0)),
  CONSTRAINT `chk_batch_step_records_return_quantity` CHECK ((`return_quantity` IS NULL) OR (`return_quantity` >= 0)),
  CONSTRAINT `chk_batch_step_records_status` CHECK (`status` in ('pending','doing','completed','abnormal','skipped'))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='批次工序报工记录表';
