/** 管理端和后端 Guard 共用的权限编码。 */
export const PERMISSIONS = {
  dashboard: {
    page: 'dashboard:page',
  },
  system: {
    page: 'system:page',
    users: {
      page: 'system:users:view',
      view: 'system:users:view',
      detail: 'system:users:detail',
      create: 'system:users:create',
      update: 'system:users:update',
      enable: 'system:users:enable',
      disable: 'system:users:disable',
      resetPassword: 'system:users:reset-password',
      assignRole: 'system:users:assign-role',
    },
    roles: {
      page: 'system:roles:view',
      view: 'system:roles:view',
      detail: 'system:roles:detail',
      create: 'system:roles:create',
      update: 'system:roles:update',
      delete: 'system:roles:delete',
      enable: 'system:roles:enable',
      disable: 'system:roles:disable',
      assignPermissions: 'system:roles:assign-permissions',
    },
    permissions: {
      page: 'system:permissions:view',
      view: 'system:permissions:view',
      detail: 'system:permissions:detail',
      create: 'system:permissions:create',
      update: 'system:permissions:update',
      delete: 'system:permissions:delete',
      enable: 'system:permissions:enable',
      disable: 'system:permissions:disable',
    },
    logs: {
      page: 'system:logs:view',
      view: 'system:logs:view',
      detail: 'system:logs:detail',
      export: 'system:logs:export',
    },
  },
  product: {
    page: 'product:page',
    products: {
      page: 'product:products:view',
      view: 'product:products:view',
      detail: 'product:products:detail',
      create: 'product:products:create',
      update: 'product:products:update',
      enable: 'product:products:enable',
      disable: 'product:products:disable',
      viewInventory: 'product:products:view-inventory',
      viewRoute: 'product:products:view-route',
      configBom: 'product:products:config-bom',
      bindRoute: 'product:products:bind-route',
    },
    categories: {
      page: 'product:categories:view',
      view: 'product:categories:view',
      detail: 'product:categories:detail',
      create: 'product:categories:create',
      update: 'product:categories:update',
      enable: 'product:categories:enable',
      disable: 'product:categories:disable',
    },
    processes: {
      page: 'product:processes:view',
      view: 'product:processes:view',
      detail: 'product:processes:detail',
      create: 'product:processes:create',
      update: 'product:processes:update',
      enable: 'product:processes:enable',
      disable: 'product:processes:disable',
      uploadSop: 'product:processes:upload-sop',
    },
    routes: {
      page: 'product:routes:view',
      view: 'product:routes:view',
      detail: 'product:routes:detail',
      create: 'product:routes:create',
      update: 'product:routes:update',
      delete: 'product:routes:delete',
      enable: 'product:routes:enable',
      disable: 'product:routes:disable',
      configProcesses: 'product:routes:config-processes',
    },
  },
  warehouse: {
    page: 'warehouse:page',
    inventory: {
      page: 'warehouse:inventory:view',
      view: 'warehouse:inventory:view',
      viewAvailable: 'warehouse:inventory:view-available',
      viewReserved: 'warehouse:inventory:view-reserved',
      stocktake: 'warehouse:inventory:stocktake',
      adjust: 'warehouse:inventory:adjust',
    },
    stocktakes: {
      page: 'warehouse:stocktakes:view',
      view: 'warehouse:stocktakes:view',
      targets: 'warehouse:stocktakes:targets',
      create: 'warehouse:stocktakes:create',
      adjust: 'warehouse:stocktakes:adjust',
    },
    finishedTransactions: {
      page: 'warehouse:finished-transactions:view',
      view: 'warehouse:finished-transactions:view',
      detail: 'warehouse:finished-transactions:detail',
      inbound: 'warehouse:finished-transactions:inbound',
      outbound: 'warehouse:finished-transactions:outbound',
      shipment: 'warehouse:finished-transactions:shipment',
    },
    materialTransactions: {
      page: 'warehouse:material-transactions:view',
      view: 'warehouse:material-transactions:view',
      detail: 'warehouse:material-transactions:detail',
      inbound: 'warehouse:material-transactions:inbound',
      outbound: 'warehouse:material-transactions:outbound',
      return: 'warehouse:material-transactions:return',
    },
  },
  production: {
    page: 'production:page',
    orders: {
      page: 'production:orders:view',
      view: 'production:orders:view',
      detail: 'production:orders:detail',
      create: 'production:orders:create',
      update: 'production:orders:update',
      draft: 'production:orders:draft',
      release: 'production:orders:release',
      close: 'production:orders:close',
      cancel: 'production:orders:cancel',
      tasks: {
        view: 'production:orders:tasks:view',
        create: 'production:orders:tasks:create',
        update: 'production:orders:tasks:update',
      },
      generateMaterialDemand: 'production:orders:generate-material-demand',
      allocateMaterial: 'production:orders:allocate-material',
    },
    tasks: {
      page: 'production:tasks:view',
      view: 'production:tasks:view',
      detail: 'production:tasks:detail',
      create: 'production:tasks:create',
      update: 'production:tasks:update',
      generateMaterialDemand: 'production:tasks:generate-material-demand',
      allocateMaterial: 'production:tasks:allocate-material',
      dispatch: 'production:tasks:dispatch',
      start: 'production:tasks:start',
      finish: 'production:tasks:finish',
      createRework: 'production:tasks:create-rework',
      viewTrace: 'production:tasks:view-trace',
    },
    materialAllocation: {
      page: 'production:material-allocation:view',
      view: 'production:material-allocation:view',
      generateDemand: 'production:material-allocation:generate-demand',
      allocate: 'production:material-allocation:allocate',
      confirmKit: 'production:material-allocation:confirm-kit',
      confirmOutbound: 'production:material-allocation:confirm-outbound',
      returnMaterial: 'production:material-allocation:return-material',
    },
    dispatch: {
      page: 'production:dispatch:view',
      view: 'production:dispatch:view',
      detail: 'production:dispatch:detail',
      assign: 'production:dispatch:assign',
      reassign: 'production:dispatch:reassign',
      batchDefault: 'production:dispatch:batch-default',
      clear: 'production:dispatch:clear',
    },
    reports: {
      page: 'production:reports:view',
      view: 'production:reports:view',
      detail: 'production:reports:detail',
      start: 'production:reports:start',
      finish: 'production:reports:finish',
      startAndFinish: 'production:reports:start-and-finish',
      batchFinish: 'production:reports:batch-finish',
    },
  },
  quality: {
    page: 'quality:page',
    inspections: {
      page: 'quality:inspections:view',
      view: 'quality:inspections:view',
      detail: 'quality:inspections:detail',
      create: 'quality:inspections:create',
      update: 'quality:inspections:update',
      uploadFile: 'quality:inspections:upload-file',
      createRework: 'quality:inspections:create-rework',
      confirmInbound: 'quality:inspections:confirm-inbound',
    },
    reworks: {
      page: 'quality:reworks:view',
      view: 'quality:reworks:view',
      detail: 'quality:reworks:detail',
      create: 'quality:reworks:create',
      update: 'quality:reworks:update',
      assignOwner: 'quality:reworks:assign-owner',
      submitResult: 'quality:reworks:submit-result',
      reinspect: 'quality:reworks:reinspect',
    },
  },
  worker: {
    tasks: {
      page: 'worker:tasks:view',
      view: 'worker:tasks:view',
      detail: 'worker:tasks:detail',
      viewSop: 'worker:tasks:view-sop',
      start: 'worker:tasks:start',
      complete: 'worker:tasks:complete',
      history: 'worker:tasks:history',
    },
  },
  inspector: {
    tasks: {
      page: 'inspector:tasks:view',
      view: 'inspector:tasks:view',
      detail: 'inspector:tasks:detail',
      viewSpec: 'inspector:tasks:view-spec',
      submitResult: 'inspector:tasks:submit-result',
      uploadFile: 'inspector:tasks:upload-file',
      createRework: 'inspector:tasks:create-rework',
    },
  },
  trace: {
    page: 'trace:page',
    view: 'trace:view',
  },
  reports: {
    page: 'reports:page',
    orderProgress: {
      page: 'reports:order-progress:view',
      view: 'reports:order-progress:view',
    },
    taskProgress: {
      page: 'reports:task-progress:view',
      view: 'reports:task-progress:view',
    },
    inventoryRecords: {
      page: 'reports:inventory-records:view',
      view: 'reports:inventory-records:view',
    },
  },
} as const;

type PermissionValue<T> = T extends string
  ? T
  : T extends Record<string, unknown>
    ? PermissionValue<T[keyof T]>
    : never;

export type PermissionCode = PermissionValue<typeof PERMISSIONS>;
