USE company_test;

CREATE TABLE IF NOT EXISTS material_batches (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '主键',
  product_id BIGINT UNSIGNED NOT NULL COMMENT '物料对应的产品ID，同一物料允许多个批次',
  material_batch_no VARCHAR(100) NOT NULL COMMENT '物料批次号',
  supplier_name VARCHAR(255) NULL COMMENT '供应商名称',
  received_date DATE NULL COMMENT '入库/接收日期',
  quantity DECIMAL(12,4) NOT NULL DEFAULT 0 COMMENT '当前库存台账数量',
  status VARCHAR(50) NOT NULL DEFAULT 'available' COMMENT 'available/partial_used/used_up/disabled',
  remark TEXT NULL COMMENT '备注',
  created_by BIGINT UNSIGNED NULL COMMENT '创建人',
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  updated_by BIGINT UNSIGNED NULL COMMENT '更新人',
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  is_deleted TINYINT NOT NULL DEFAULT 0 COMMENT '软删除标记',
  deleted_by BIGINT UNSIGNED NULL COMMENT '删除人',
  deleted_at DATETIME NULL COMMENT '删除时间',
  PRIMARY KEY (id),
  UNIQUE KEY uk_material_batches_no_deleted (material_batch_no, is_deleted),
  KEY idx_material_batches_product_id (product_id),
  KEY idx_material_batches_supplier_name (supplier_name),
  KEY idx_material_batches_status (status),
  KEY idx_material_batches_is_deleted (is_deleted),
  KEY idx_material_batches_created_by (created_by),
  KEY idx_material_batches_updated_by (updated_by),
  KEY idx_material_batches_deleted_by (deleted_by),
  CONSTRAINT fk_material_batches_product_id FOREIGN KEY (product_id) REFERENCES products (id),
  CONSTRAINT fk_material_batches_created_by FOREIGN KEY (created_by) REFERENCES users (id) ON DELETE SET NULL,
  CONSTRAINT fk_material_batches_updated_by FOREIGN KEY (updated_by) REFERENCES users (id) ON DELETE SET NULL,
  CONSTRAINT fk_material_batches_deleted_by FOREIGN KEY (deleted_by) REFERENCES users (id) ON DELETE SET NULL,
  CONSTRAINT chk_material_batches_status CHECK (status IN ('available', 'partial_used', 'used_up', 'disabled')),
  CONSTRAINT chk_material_batches_quantity CHECK (quantity >= 0)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='物料批次表';

CREATE TABLE IF NOT EXISTS batch_material_usages (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '主键',
  batch_id BIGINT UNSIGNED NULL COMMENT '生产批次ID，production_batches 表建立后补外键',
  material_batch_id BIGINT UNSIGNED NOT NULL COMMENT '物料批次ID',
  reserved_quantity DECIMAL(12,4) NOT NULL DEFAULT 0 COMMENT '预留数量',
  used_quantity DECIMAL(12,4) NOT NULL DEFAULT 0 COMMENT '实际使用数量',
  unit VARCHAR(50) NULL COMMENT '单位',
  status VARCHAR(50) NOT NULL DEFAULT 'reserved' COMMENT 'reserved/part_used/used/cancelled',
  recorded_by BIGINT UNSIGNED NULL COMMENT '记录人',
  recorded_at DATETIME NULL COMMENT '记录时间',
  remark TEXT NULL COMMENT '备注',
  created_by BIGINT UNSIGNED NULL COMMENT '创建人',
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  updated_by BIGINT UNSIGNED NULL COMMENT '更新人',
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  is_deleted TINYINT NOT NULL DEFAULT 0 COMMENT '软删除标记',
  deleted_by BIGINT UNSIGNED NULL COMMENT '删除人',
  deleted_at DATETIME NULL COMMENT '删除时间',
  PRIMARY KEY (id),
  KEY idx_batch_material_usages_batch_id (batch_id),
  KEY idx_batch_material_usages_material_batch_id (material_batch_id),
  KEY idx_batch_material_usages_status (status),
  KEY idx_batch_material_usages_recorded_by (recorded_by),
  KEY idx_batch_material_usages_is_deleted (is_deleted),
  KEY idx_batch_material_usages_created_by (created_by),
  KEY idx_batch_material_usages_updated_by (updated_by),
  KEY idx_batch_material_usages_deleted_by (deleted_by),
  CONSTRAINT fk_batch_material_usages_material_batch_id FOREIGN KEY (material_batch_id) REFERENCES material_batches (id),
  CONSTRAINT fk_batch_material_usages_recorded_by FOREIGN KEY (recorded_by) REFERENCES users (id) ON DELETE SET NULL,
  CONSTRAINT fk_batch_material_usages_created_by FOREIGN KEY (created_by) REFERENCES users (id) ON DELETE SET NULL,
  CONSTRAINT fk_batch_material_usages_updated_by FOREIGN KEY (updated_by) REFERENCES users (id) ON DELETE SET NULL,
  CONSTRAINT fk_batch_material_usages_deleted_by FOREIGN KEY (deleted_by) REFERENCES users (id) ON DELETE SET NULL,
  CONSTRAINT chk_batch_material_usages_status CHECK (status IN ('reserved', 'part_used', 'used', 'cancelled')),
  CONSTRAINT chk_batch_material_usages_reserved_quantity CHECK (reserved_quantity >= 0),
  CONSTRAINT chk_batch_material_usages_used_quantity CHECK (used_quantity >= 0)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='生产批次物料预留与使用表';
