USE company_test;

CREATE TABLE IF NOT EXISTS product_materials (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '主键',
  product_id BIGINT UNSIGNED NOT NULL COMMENT '产品ID',
  material_product_id BIGINT UNSIGNED NOT NULL COMMENT '物料产品ID',
  quantity_per_unit DECIMAL(12,4) NOT NULL COMMENT '单位用量',
  unit VARCHAR(50) NULL COMMENT '单位',
  is_key_material TINYINT NOT NULL DEFAULT 1 COMMENT '是否关键物料',
  need_batch_record TINYINT NOT NULL DEFAULT 1 COMMENT '是否记录批次',
  remark TEXT NULL COMMENT '备注',
  created_by BIGINT UNSIGNED NULL COMMENT '创建人',
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  updated_by BIGINT UNSIGNED NULL COMMENT '更新人',
  updated_at DATETIME NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  is_deleted TINYINT NOT NULL DEFAULT 0 COMMENT '软删除标记',
  deleted_by BIGINT UNSIGNED NULL COMMENT '删除人',
  deleted_at DATETIME NULL COMMENT '删除时间',
  PRIMARY KEY (id),
  UNIQUE KEY uk_product_materials_product_material_deleted (product_id, material_product_id, is_deleted),
  KEY idx_product_materials_product_id (product_id),
  KEY idx_product_materials_material_product_id (material_product_id),
  KEY idx_product_materials_is_deleted (is_deleted),
  KEY idx_product_materials_created_by (created_by),
  KEY idx_product_materials_updated_by (updated_by),
  KEY idx_product_materials_deleted_by (deleted_by),
  CONSTRAINT fk_product_materials_product_id FOREIGN KEY (product_id) REFERENCES products (id) ON DELETE CASCADE,
  CONSTRAINT fk_product_materials_material_product_id FOREIGN KEY (material_product_id) REFERENCES products (id) ON DELETE RESTRICT,
  CONSTRAINT fk_product_materials_created_by FOREIGN KEY (created_by) REFERENCES users (id) ON DELETE SET NULL,
  CONSTRAINT fk_product_materials_updated_by FOREIGN KEY (updated_by) REFERENCES users (id) ON DELETE SET NULL,
  CONSTRAINT fk_product_materials_deleted_by FOREIGN KEY (deleted_by) REFERENCES users (id) ON DELETE SET NULL,
  CONSTRAINT chk_product_materials_quantity CHECK (quantity_per_unit > 0)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='产品物料清单表';

CREATE TABLE IF NOT EXISTS route_step_materials (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '主键',
  route_step_id BIGINT UNSIGNED NOT NULL COMMENT '工艺路线工序明细ID',
  product_material_id BIGINT UNSIGNED NOT NULL COMMENT '产品物料清单ID',
  remark TEXT NULL COMMENT '备注',
  created_by BIGINT UNSIGNED NULL COMMENT '创建人',
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  updated_by BIGINT UNSIGNED NULL COMMENT '更新人',
  updated_at DATETIME NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  is_deleted TINYINT NOT NULL DEFAULT 0 COMMENT '软删除标记',
  deleted_by BIGINT UNSIGNED NULL COMMENT '删除人',
  deleted_at DATETIME NULL COMMENT '删除时间',
  PRIMARY KEY (id),
  UNIQUE KEY uk_route_step_materials_step_material_deleted (route_step_id, product_material_id, is_deleted),
  KEY idx_route_step_materials_route_step_id (route_step_id),
  KEY idx_route_step_materials_product_material_id (product_material_id),
  KEY idx_route_step_materials_is_deleted (is_deleted),
  KEY idx_route_step_materials_created_by (created_by),
  KEY idx_route_step_materials_updated_by (updated_by),
  KEY idx_route_step_materials_deleted_by (deleted_by),
  CONSTRAINT fk_route_step_materials_route_step_id FOREIGN KEY (route_step_id) REFERENCES process_route_steps (id) ON DELETE CASCADE,
  CONSTRAINT fk_route_step_materials_product_material_id FOREIGN KEY (product_material_id) REFERENCES product_materials (id) ON DELETE CASCADE,
  CONSTRAINT fk_route_step_materials_created_by FOREIGN KEY (created_by) REFERENCES users (id) ON DELETE SET NULL,
  CONSTRAINT fk_route_step_materials_updated_by FOREIGN KEY (updated_by) REFERENCES users (id) ON DELETE SET NULL,
  CONSTRAINT fk_route_step_materials_deleted_by FOREIGN KEY (deleted_by) REFERENCES users (id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='工序用料关联表';

CREATE TABLE IF NOT EXISTS batch_step_records (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '主键',
  batch_id BIGINT UNSIGNED NOT NULL COMMENT '生产批次ID',
  route_step_id BIGINT UNSIGNED NOT NULL COMMENT '工艺路线工序明细ID',
  step_order INT NOT NULL COMMENT '工序顺序',
  process_id BIGINT UNSIGNED NULL COMMENT '工序ID',
  process_code VARCHAR(64) NOT NULL COMMENT '工序编码',
  process_name VARCHAR(128) NOT NULL COMMENT '工序名称',
  default_owner_id BIGINT UNSIGNED NULL COMMENT '默认负责人',
  actual_owner_id BIGINT UNSIGNED NULL COMMENT '实际负责人',
  status VARCHAR(50) NOT NULL DEFAULT 'pending' COMMENT 'pending/assigned/doing/completed/abnormal/skipped',
  started_at DATETIME NULL COMMENT '开工时间',
  finished_at DATETIME NULL COMMENT '完工时间',
  total_quantity DECIMAL(12,4) NULL COMMENT '报工总数',
  qualified_quantity DECIMAL(12,4) NULL COMMENT '合格数量',
  defective_quantity DECIMAL(12,4) NULL COMMENT '不合格数量',
  remark TEXT NULL COMMENT '备注',
  created_by BIGINT UNSIGNED NULL COMMENT '创建人',
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  updated_by BIGINT UNSIGNED NULL COMMENT '更新人',
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  is_deleted TINYINT NOT NULL DEFAULT 0 COMMENT '软删除标记',
  deleted_by BIGINT UNSIGNED NULL COMMENT '删除人',
  deleted_at DATETIME NULL COMMENT '删除时间',
  PRIMARY KEY (id),
  UNIQUE KEY uk_batch_step_records_batch_step_deleted (batch_id, route_step_id, is_deleted),
  KEY idx_batch_step_records_batch_id (batch_id),
  KEY idx_batch_step_records_route_step_id (route_step_id),
  KEY idx_batch_step_records_process_id (process_id),
  KEY idx_batch_step_records_default_owner_id (default_owner_id),
  KEY idx_batch_step_records_actual_owner_id (actual_owner_id),
  KEY idx_batch_step_records_status (status),
  KEY idx_batch_step_records_is_deleted (is_deleted),
  KEY idx_batch_step_records_created_by (created_by),
  KEY idx_batch_step_records_updated_by (updated_by),
  KEY idx_batch_step_records_deleted_by (deleted_by),
  CONSTRAINT fk_batch_step_records_batch_id FOREIGN KEY (batch_id) REFERENCES production_batches (id) ON DELETE CASCADE,
  CONSTRAINT fk_batch_step_records_route_step_id FOREIGN KEY (route_step_id) REFERENCES process_route_steps (id) ON DELETE RESTRICT,
  CONSTRAINT fk_batch_step_records_process_id FOREIGN KEY (process_id) REFERENCES processes (id) ON DELETE SET NULL,
  CONSTRAINT fk_batch_step_records_default_owner_id FOREIGN KEY (default_owner_id) REFERENCES users (id) ON DELETE SET NULL,
  CONSTRAINT fk_batch_step_records_actual_owner_id FOREIGN KEY (actual_owner_id) REFERENCES users (id) ON DELETE SET NULL,
  CONSTRAINT fk_batch_step_records_created_by FOREIGN KEY (created_by) REFERENCES users (id) ON DELETE SET NULL,
  CONSTRAINT fk_batch_step_records_updated_by FOREIGN KEY (updated_by) REFERENCES users (id) ON DELETE SET NULL,
  CONSTRAINT fk_batch_step_records_deleted_by FOREIGN KEY (deleted_by) REFERENCES users (id) ON DELETE SET NULL,
  CONSTRAINT chk_batch_step_records_status CHECK (status IN ('pending', 'assigned', 'doing', 'completed', 'abnormal', 'skipped')),
  CONSTRAINT chk_batch_step_records_total_quantity CHECK (total_quantity IS NULL OR total_quantity >= 0),
  CONSTRAINT chk_batch_step_records_qualified_quantity CHECK (qualified_quantity IS NULL OR qualified_quantity >= 0),
  CONSTRAINT chk_batch_step_records_defective_quantity CHECK (defective_quantity IS NULL OR defective_quantity >= 0)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='批次报工记录表';
